{"name": "Проверка изменения данных авторизированного пользователя", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "self = <test_login.TestLogin object at 0x0000023E5EABA500>, creta_user = <Response [403]>\n\n    @allure.title('Проверка изменения данных авторизированного пользователя')\n    def test_changest_log_in_user_data(self, creta_user):  # тест не проходит через комаду обшего запуска но в соло работает не понял причину\n        respons =requests.patch(Urls.BASE_URL + Urls.CHANGEST_USER_DATA,\n>                      headers= {\"Authorization\": creta_user.json()['accessToken']}, json=DataLogin.CHANGEST_USER_NAME)\nE       KeyError: 'accessToken'\n\ntests\\test_login.py:21: KeyError"}, "start": 1717603397844, "stop": 1717603397845, "uuid": "90724cd9-859e-4f90-8a75-9b6ac16996aa", "historyId": "e02162115e98ad5484b856d71c89d13e", "testCaseId": "e02162115e98ad5484b856d71c89d13e", "fullName": "tests.test_login.TestLogin#test_changest_log_in_user_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-SKP7F9T"}, {"name": "thread", "value": "8928-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}